app/api/models.py
from app import db


class BaseMixin(object):
    """Useful methods to include

    https://gist.github.com/techniq/5174410
    """
    @classmethod
    def get_by(cls, **kw):
        return cls.query.filter_by(**kw).first()

    @classmethod
    def get_or_create(cls, **kw):
        r = cls.get_by(**kw)
        if not r:
            r = cls(**kw)
            db.session.add(r)
        return r

    def populate_from_object(self, obj):
        for n in self.__table__.c.keys():
            if hasattr(obj, n):
                setattr(self, n, getattr(obj, n))

    def __repr__(self):
        values = ', '.join("{0}={1}".format(n, getattr(self, n))
                           for n in self.__table__.c.keys())
        return "{0}({1})".format(self.__class__.__name__, values)

ApiCharacter = db.Table(
    'api_apicharacter',
    db.Column('characterID', db.Integer,
              db.ForeignKey('api_character.characterID')),
    db.Column('keyID', db.Integer, db.ForeignKey('api_api.keyID'))
)

ApiCorporation = db.Table(
    'api_apicorporation',
    db.Column('corporationID', db.Integer,
              db.ForeignKey('api_corporation.corporationID')),
    db.Column('keyID', db.Integer, db.ForeignKey('api_api.keyID'))
)


class Api(BaseMixin, db.Model):
    __tablename__ = 'api_api'
    keyID = db.Column(db.Integer, primary_key=True)
    vCode = db.Column(db.String(80))
    accessMask = db.Column(db.Integer)
    expires = db.Column(db.DateTime)
    type = db.Column(
        db.Enum('Account', 'Character', 'Corporation', name='api_apitypes'))


class Character(BaseMixin, db.Model):
    __tablename__ = 'api_character'
    characterID = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    homeStationID = db.Column(db.Integer)
    DoB = db.Column(db.DateTime)
    race = db.Column(db.String(8))
    bloodLine = db.Column(db.String(20))
    ancestry = db.Column(db.String(20))
    gender = db.Column(db.String(6))
    corporationName = db.Column(db.String(80))
    corporationID = db.Column(db.Integer)
    allianceName = db.Column(db.String(80))
    allianceID = db.Column(db.Integer)
    factionName = db.Column(db.String(80))
    factionID = db.Column(db.Integer)
    cloneTypeID = db.Column(db.Integer)
    cloneName = db.Column(db.String(20))
    cloneSkillPoints = db.Column(db.Integer)
    freeSkillPoints = db.Column(db.Integer)
    freeRespecs = db.Column(db.Integer)
    cloneJumpDate = db.Column(db.DateTime)
    lastRespecDate = db.Column(db.DateTime)
    lastTimedRespec = db.Column(db.DateTime)
    remoteStationDate = db.Column(db.DateTime)
    jumpActivation = db.Column(db.DateTime)
    jumpFatigue = db.Column(db.DateTime)
    jumpLastUpdate = db.Column(db.DateTime)
    balance = db.Column(db.Numeric(12, 2))
    apis = db.relationship('Api', secondary=ApiCharacter, backref='characters')


class Corporation(BaseMixin, db.Model):
    __tablename__ = 'api_corporation'
    corporationID = db.Column(db.Integer, primary_key=True)
    corporationName = db.Column(db.String(80))
    ticker = db.Column(db.String(5))
    ceoID = db.Column(db.Integer)
    ceoName = db.Column(db.String(80))
    stationID = db.Column(db.Integer)
    stationName = db.Column(db.String(80))
    description = db.Column(db.String(80))
    url = db.Column(db.String(80))
    allianceID = db.Column(db.Integer)
    factionID = db.Column(db.Integer)
    taxRate = db.Column(db.Float)
    memberCount = db.Column(db.Integer)
    memberLimit = db.Column(db.Integer)
    shares = db.Column(db.Integer)
    apis = db.relationship('Api', secondary=ApiCorporation,
                           backref='corporations')
    # TODO, each api can actually only have a single corporation? is this
    # important?


class Transaction(BaseMixin, db.Model):
    __tablename__ = 'api_transaction'
    transactionDateTime = db.Column(db.DateTime)
    transactionID = db.Column(db.Integer, primary_key=True)
    quantity = db.Column(db.Integer)
    typeName = db.Column(db.String(80))
    typeID = db.Column(db.Integer)
    price = db.Column(db.Numeric(12, 2))
    clientID = db.Column(db.Integer)
    clientName = db.Column(db.String(80))
    stationID = db.Column(db.Integer)
    stationName = db.Column(db.String(80))
    transactionType = db.Column(
        db.Enum("buy", "sell", name='api_transactiontypes'))
    transactionFor = db.Column(
        db.Enum("personal", "corporation", name='api_transactiontypes'))
    journalTransactionID = db.Column(db.BigInteger)
    clientTypeID = db.Column(db.Integer)

    characterID = db.Column(
        db.Integer, db.ForeignKey('api_character.characterID'), nullable=True)
    character = db.relationship("Character", backref="transactions")

    corporationID = db.Column(
        db.Integer, db.ForeignKey('api_corporation.corporationID'),
        nullable=True)
    corporation = db.relationship("Corporation", backref="transactions")


class Order(BaseMixin, db.Model):
    __tablename__ = 'api_order'
    orderID = db.Column(db.Integer, primary_key=True)
    clientTypeID = db.Column(db.Integer)
    stationID = db.Column(db.Integer)
    volEntered = db.Column(db.Integer)
    volRemaining = db.Column(db.Integer)
    minVolume = db.Column(db.Integer)
    orderState = db.Column(db.Integer)
    typeID = db.Column(db.Integer)
    range = db.Column(db.Integer)
    accountKey = db.Column(db.Integer)
    duration = db.Column(db.Integer)
    escrow = db.Column(db.Numeric(12, 2))
    price = db.Column(db.Numeric(12, 2))
    bid = db.Column(db.Boolean)
    issued = db.Column(db.DateTime)

    # API returns charID :/
    charID = db.Column(
        db.Integer, db.ForeignKey('api_character.characterID'), nullable=True)
    character = db.relationship("Character", backref="orders")

    corporationID = db.Column(
        db.Integer, db.ForeignKey('api_corporation.corporationID'),
        nullable=True)
    corporation = db.relationship("Corporation", backref="orders")

app/api/forms.py
import flask_wtf as wtf  # from flask.ext.wtf import Form
from wtforms import fields
from wtforms.validators import InputRequired, ValidationError
import eveapi

from .models import Api


class ApiForm(wtf.Form):
    keyID = fields.IntegerField("API ID", validators=[InputRequired()])
    vCode = fields.StringField("VCode", validators=[InputRequired()])

    def validate_keyID(self, field):
        api = Api.query.filter(Api.keyID == field.data).first()
        if api is not None:
            raise ValidationError("That API key already exists")

    def validate_vCode(self, field):
        auth = eveapi.EVEAPIConnection().auth(keyID=self.keyID.data,
                                              vCode=self.vCode.data)
        try:
            APIKeyInfo = auth.account.APIKeyInfo()
        except eveapi.Error:
            raise ValidationError("Invalid API.")  # TODO better reasons

        # keep api information on form object
        self.key = APIKeyInfo.key

app/api/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask.ext.login import login_required

from sqlalchemy.exc import IntegrityError

from app import db
from .forms import ApiForm
from .models import Api, Character, Corporation, Transaction, Order
import tasks

api = Blueprint('api', __name__)


@api.route('/api')
@login_required
def apis():
    ''' List of APIs '''
    api_keys = db.session.query(Api).all()
    return render_template('api/api.html', title="APIs", data=api_keys)


@api.route('/api_add', methods=['GET', 'POST'])
@login_required
def add():
    ''' Adds an API to the db'''
    form = ApiForm()
    if form.validate_on_submit():
        api = Api()
        form.populate_obj(api)
        api.populate_from_object(form.key)
        if api.type in ('Account', 'Character'):
            for c in form.key.characters:
                character = Character.get_or_create(characterID=c.characterID)
                character.populate_from_object(c)
                api.characters.append(character)
                tasks.character_sheet.apply_async(
                    countdown=1,
                    kwargs={'keyID': form.keyID.data,
                            'vCode': form.vCode.data,
                            'characterID': c.characterID}
                )
        if api.type == 'Corporation':
            c = form.key.characters[0]
            corporation = Corporation.get_or_create(
                corporationID=c.corporationID)
            corporation.populate_from_object(c)
            api.corporations.append(corporation)
            tasks.corporation_sheet.apply_async(
                countdown=1,
                kwargs={'keyID': form.keyID.data,
                        'vCode': form.vCode.data}
            )
        db.session.add(api)
        db.session.commit()
        return redirect(url_for('api.apis'))
    return render_template('api/add.html', form=form)


@api.route('/api_delete/<api_id>')
@login_required
def delete(api_id):
    ''' removes an API from the db'''
    this_api = db.session.query(Api).get(api_id)
    if api is None:
        flash('API Error', 'error')
        return redirect(url_for('api.apis'))
    db.session.delete(this_api)
    try:
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash('API Error', 'error')
    return redirect(url_for('api.apis'))


@api.route('/api_refresh/<api_id>')
@login_required
def refresh(api_id):
    ''' refresh an API'''
    tasks.refresh_all.apply_async(kwargs={'keyID': api_id})
    return redirect(url_for('api.apis'))


@api.route('/characters')
@login_required
def characters():
    ''' List characters in db linked to this user '''
    chars = db.session.query(Character).all()
    return render_template(
        'api/characters.html',
        title="Characters",
        data=chars)


@api.route('/character/<character_id>')
@login_required
def character(character_id):
    '''Detailed look at a chacter'''
    character = db.session.query(Character).get(character_id)
    return render_template(
        'api/character.html',
        title=character.name,
        character=character)


@api.route('/corporations')
@login_required
def corporations():
    ''' List corporations in db linked to this user '''
    corps = db.session.query(Corporation).all()
    return render_template(
        'api/corporations.html',
        title="corporations",
        data=corps)


@api.route('/transactions')
@login_required
def transactions():
    # TODO this returns all transactions currently, need to think about this
    data = db.session.query(Transaction).all()
    return render_template(
        'api/transactions.html',
        title="Transactions",
        data=data)


@api.route('/orders')
@login_required
def orders():
    data = db.session.query(Order).all()
    return render_template('api/orders.html', title="Orders", data=data)

app/templates/api/add.html
{% extends "base.html" %}
{% import "helpers/forms.html" as forms %}
{% block content %}
{{super()}}
<form action="{{url_for('api.add')}}" method="POST">
    {{ forms.render(form) }}
    <button type="Submit" class="btn btn-default">Submit</button>
</form>
{% endblock content %}

app/templates/api/api.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
              <h1>API Keys</h1>
            </div>          

            <table class="table">
                <thead>
                    <th scope="col">ID</th>
                    <th scope="col">Verification Code</th>
                    <th scope="col">Type</th>
                    <th scope="col">Access Mask</th>
                    <th scope="col">Expires</th>
                    <th scope="col"> </th>
                </thead>
                <tbody>
                    {% for api in data %}  
                        <tr>
                        <td>{{api.keyID}}</td>
                        <td>{{api.vCode}}</td>
                        <td>{{api.type}}</td>
                        <td>{{api.accessMask}}</td>
                        <td>{{api.expires}}</td>
                        <td><a href="api_refresh/{{api.keyID}}"><span
                                    class="glyphicon
                                    glyphicon-refresh"></span></a> <a href="api_delete/{{api.keyID}}"><span class="glyphicon glyphicon-remove"></span></a></td>
                        </tr>
                    {% endfor %}
                <tbody>
            </table>
        </div><!--/col-md--->
        <div class="col-md-2 col-md-offset-9">
            <a href="/api_refresh_all"><button type="button" class="btn btn-default">Refresh All</button></a>
            <a href="/api_add"><button type="button" class="btn btn-primary">Add</button></a>
        </div><!--/col-md--->
    </div><!--/row-->
{% endblock %}

app/templates/api/character.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>{{character.name}}</h1>
            </div>
            Corporation: {{character.corporationName}}
            <br>
            Alliance: {{character.allianceName}}
            <br>
            {{character}}
        </div><!--/col-md--->
    </div><!--/row-->
{% endblock %}

app/templates/api/characters.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1>Characters</h1>
            </div>
            <div class="row">
            {% for c in data %}
                <div class="col-sm-4 col-md-3">
                    <div class="thumbnail">
                        <img src="http://image.eveonline.com/Character/{{c.characterID}}_256.jpg" class="img-responsive">
                        <div class="caption">
                            <a href="character/{{c.characterID}}"><h3>{{c.name}}</h3></a>
                            <p>{{c.corporationName}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div><!--/col-md-12-->
    </div><!--/row-->
{% endblock %}

app/templates/api/corporations.html
{% extends "base.html" %}
{% block content %}    
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
              <h1>Corporations</h1>
            </div>   
              {% for c in data %}         
              <div class="col-sm-4 col-md-3">
                <div class="thumbnail">
                  <img src="http://image.eveonline.com/Corporation/{{c.corporationID}}_128.png" class="img-responsive">
                  <div class="caption">
                    <h3>{{c.corporationName}} <small>[{{c.ticker}}]</small></h3>
                    <p>{{c}}</p>
                  </div>
                </div>
              </div>
              {% endfor %} 
        </div><!--/col-md-12-->
    </div><!--/row-->
{% endblock %}

app/templates/api/orders.html
{% extends "base.html" %}

{% block extra_head %}
<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.4/css/jquery.dataTables.css">
<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.js"></script>

<script type="text/javascript">
    $(document).ready( 
        function () { 
            $('#example').DataTable(); 
        } 
    );
</script>

{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>Market Orders <small>tag</small></h1>
            </div>    
            
            <table class="table" id="example">     
                <thead>
                    <th scope="col">Corporation</th>
                    <th scope="col">Character</th>
                    <th scope="col">b/s</th>
                    <th scope="col">Date</th>
                    <th scope="col">Item</th>
                    <th class="ral" scope="col">Price</th>
                    <th class="ral" scope="col">n</th>
                    <th class="ral" scope="col">Total</th>
                    <th scope="col">Station</th>
                </thead>
                <tbody>
                    {% for row in data %}  
                    <tr> 
                    <td><a href="/corp/{{row.corpID}}">{{row.corporation.name}}</a></td>
                    <td><a href="/char/{{row.charID}}">{{row.character.name}}</a></td>
                    <td>{{row.bid}}</td>
                    <td>{{row.issued}}</td>
                    <td><a href="/item/{{row.typeID}}">{{row.typeID}}</a></td>
                    <td class="ral">{{'{:20,.2f}'.format(row.price)}}</td>
                    <td class="ral">{{row.volRemaining}}</td>
                    <td class="ral">{{'{:20,.2f}'.format(row.price*row.volRemaining)}} </td>
                    <td><a href="/station/{{row.stationID}}">{{row.stationID}}</a></td> 
                    </tr> 
                    {% endfor %} 
                <tbody>
            </table>
        </div><!--/col-md-->
    </div><!--/row-->
{% endblock %}

app/templates/api/transactions.html
{% extends "base.html" %}

{% block extra_head %}
<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.4/css/jquery.dataTables.css">
<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.js"></script>

<script type="text/javascript">
    $(document).ready( 
        function () { 
            $('#example').DataTable(); 
        } 
    );
</script>

{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>Transactions <small>from wallet</small></h1>
            </div>    
            
            <table class="table" id="example">     
                <thead>
                    <th scope="col">For</th>
                    <th scope="col">Corporation</th>
                    <th scope="col">Character</th>
                    <th scope="col">b/s</th>
                    <th scope="col">Date</th>
                    <th scope="col">Item</th>
                    <th class="ral" scope="col">Price</th>
                    <th class="ral" scope="col">n</th>
                    <th class="ral" scope="col">Total</th>
                    <th scope="col">Station</th>
                </thead>
                <tbody>
                    {% for row in data %}  
                    <tr> 
                    <td>{{row.transactionFor}}</td>
                    <td><a href="/corp/{{row.corporationID}}">{{row.corporation.corporationName}}</a></td>
                    <td><a href="/char/{{row.characterID}}">{{row.character.name}}</a></td>
                    <td>{{row.transactionType}}</td>
                    <td>{{row.transactionDateTime}}</td>
                    <td><a href="/item/{{row.typeID}}">{{row.typeName}}</a></td>
                    <td class="ral">{{'{:20,.2f}'.format(row.price)}}</td>
                    <td class="ral">{{row.quantity}}</td>
                    {% if row.transactionType==2 %}  
                    <td class="ral"><p class="text-success"> {{'{:20,.2f}'.format(row.quantity*row.price)}} </p></td>
                    {% else %}  
                    <td class="ral"><p class="text-danger"> {{'{:20,.2f}'.format(row.quantity*row.price)}} </p></td>
                    {% endif %}  
                    <td><a href="/station/{{row.stationID}}">{{row.stationName}}</a></td> 
                    </tr> 
                    {% endfor %} 
                <tbody>
            </table>
        </div><!--/col-md-->
    </div><!--/row-->
{% endblock %}