app/crest/models.py
from sqlalchemy.ext.hybrid import hybrid_property

from app import db
from app.api.models import BaseMixin


class Item(BaseMixin, db.Model):
    __tablename__ = 'crest_item'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    adjustedPrice = db.Column(db.Numeric(12, 2))
    averagePrice = db.Column(db.Numeric(12, 2))
    href = db.Column(db.String(80))
    volume = db.Column(db.Float)
    published = db.Column(db.Boolean)


class Region(BaseMixin, db.Model):
    __tablename__ = 'crest_region'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    href = db.Column(db.String(80))


class System(BaseMixin, db.Model):
    __tablename__ = 'crest_system'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    href = db.Column(db.String(80))
    region_id = db.Column(db.Integer)


class Station(BaseMixin, db.Model):
    __tablename__ = 'crest_station'
    facilityID = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    solarSystem_id = db.Column(db.Integer)
    region_id = db.Column(db.Integer)
    type_id = db.Column(db.Integer)


class MarketHistory(BaseMixin, db.Model):
    __tablename__ = 'crest_markethistory'
    type_id = db.Column(db.Integer, primary_key=True)
    region_id = db.Column(db.Integer, primary_key=True)
    average_volume = db.Column(db.Float)
    average_orders = db.Column(db.Float)
    average_price = db.Column(db.Numeric(12, 2))

    @hybrid_property
    def price_volume(self):
        return self.average_price * self.average_volume


class MarketStat(BaseMixin, db.Model):
    __tablename__ = 'crest_marketstat'
    type_id = db.Column(db.Integer, primary_key=True)
    station_id = db.Column(db.Integer, primary_key=True)
    region_id = db.Column(db.Integer)  # denormalized
    current_buy = db.Column(db.Numeric(12, 2))
    current_buy_percentile = db.Column(db.Numeric(12, 2))
    current_buy_orders = db.Column(db.Integer)
    current_buy_volume = db.Column(db.Integer)
    current_sell = db.Column(db.Numeric(12, 2))
    current_sell_percentile = db.Column(db.Numeric(12, 2))
    current_sell_orders = db.Column(db.Integer)
    current_sell_volume = db.Column(db.Integer)

app/crest/forms.py
import flask_wtf as wtf  # from flask.ext.wtf import Form
from wtforms import fields
from wtforms.validators import InputRequired


class SearchForm(wtf.Form):
    search_term = fields.StringField(
        "Search term",
        validators=[InputRequired()])


class ImportForm(wtf.Form):
    destination = fields.SelectField(u'Destination', coerce=int)
    source = fields.SelectField(
        u'Source',
        coerce=int,
        choices=[
            (60003760, u'Jita IV - Moon 4 - Caldari Navy Assembly Plant'),
            (60008494, u'Amarr VIII (Oris) - Emperor Family Academy'),
        ]
    )
    cost = fields.IntegerField('Cost')


class UpdateForm(wtf.Form):
    task = fields.SelectField(
        u'Task',
        coerce=int,
        choices=[
            (0, u'Update Items'),
            (1, u'Update Map'),
            (2, u'Update Market Prices (Universe Average)'),
            (3, u'Update Item Details'),
        ]
    )


class UpdateMarketForm(wtf.Form):
    region = fields.SelectField(u'Region', coerce=int)
    task = fields.SelectField(
        u'Task',
        coerce=int,
        choices=[
            (0, u'Update Market History'),
            (1, u'Update Market Stats'),
        ]
    )
    items = fields.SelectField(
        u'Items',
        coerce=int,
        choices=[
            (0, u'All'),
            (1, u'Popular Only'),
            (2, u'Favourites Only'),
        ]
    )

app/crest/views.py
from flask import Blueprint, redirect, render_template, url_for
from flask.ext.login import login_required

from sqlalchemy.orm import aliased

from pycrest.eve import APIObject

from app import eve, db
from .models import Item, Region, System, Station, MarketHistory, MarketStat
from .forms import SearchForm, ImportForm, UpdateForm, UpdateMarketForm
import tasks
from app.sso.tools import dump_connection, auth_connection


crest = Blueprint('crest', __name__)


@crest.route('/update_item_details')
@login_required
def update_item_details():
    test_href = "https://public-crest.eveonline.com/types/34/"
    tasks.update_item_details.apply_async(args=(test_href,))
    return redirect(url_for('index'))


@crest.route('/update_items')
@login_required
def update_items():
    tasks.update_items.apply_async()
    return redirect(url_for('index'))


@crest.route('/update_item_prices')
@login_required
def update_item_prices():
    tasks.update_item_prices.apply_async()
    return redirect(url_for('index'))


@crest.route('/update_map')
@login_required
def update_map():
    tasks.update_map.apply_async()
    return redirect(url_for('index'))


@crest.route('/update_history/<int:region_id>')
@login_required
def update_history(region_id):
    tasks.update_market_history.apply_async(args=(region_id, 34))
    return redirect(url_for('index'))


@crest.route('/update_all_history/<int:region_id>')
@login_required
def update_all_history(region_id):
    tasks.update_all_market_history.apply_async(args=(region_id,))
    return redirect(url_for('index'))


@crest.route('/update_stat/<int:region_id>')
@login_required
def update_stat(region_id):
    with auth_connection() as con:
        auth_dump = dump_connection(con)
    tasks.update_market_stat.apply_async(args=(auth_dump, region_id, 34))
    return redirect(url_for('index'))


@crest.route('/update_all_stat/<int:region_id>')
@login_required
def update_all_stat(region_id):
    with auth_connection() as con:
        auth_dump = dump_connection(con)
    tasks.update_all_market_stat.apply_async(args=(auth_dump, region_id))
    return redirect(url_for('index'))


@crest.route('/item/<int:type_id>')
@login_required
def view_item(type_id):
    item = db.session.query(Item).get(type_id)
    crest_item = APIObject(eve.get(item.href), eve)
    market_history = MarketHistory.get_by(type_id=type_id, region_id=10000002)
    market_stat = MarketStat.get_by(type_id=type_id, station_id=60003760)
    return render_template(
        'crest/item_types.html',
        title=item.name,
        item=item,
        crest_item=crest_item(),
        market_history=market_history,
        market_stat=market_stat)


@crest.route('/station/<int:station_id>')
@login_required
def view_station(station_id):
    station = db.session.query(Station).get(station_id)
    return render_template(
        'crest/station.html',
        title=station.name,
        station=station,
        crest_station=None)


@crest.route('/import', methods=['POST', 'GET'])
@login_required
def import_tool():

    form = ImportForm()

    all_stations = db.session.query(Station.facilityID, Station.name)\
        .order_by(Station.name)\
        .all()
    form.destination.choices = (all_stations)

    if form.validate_on_submit():
        dest_market_stat = aliased(MarketStat)
        source_market_stat = aliased(MarketStat)

        dest_market_history = aliased(MarketHistory)
        source_market_history = aliased(MarketHistory)

        dest_station = aliased(Station)
        source_station = aliased(Station)

        dest_region = aliased(Region)
        source_region = aliased(Region)

        data = db.session.query(Item, dest_market_stat, source_market_stat,
                                dest_market_history, source_market_history,
                                source_market_stat.current_sell*1.2,
                                )\
            .filter(source_region.id == source_station.region_id)\
            .filter(dest_region.id == dest_station.region_id)\
            .filter(source_market_stat.type_id == Item.id)\
            .filter(source_market_stat.station_id == source_station.facilityID)\
            .filter(source_market_stat.current_sell != None)\
            .filter(dest_market_stat.type_id == Item.id)\
            .filter(dest_market_stat.station_id == dest_station.facilityID)\
            .filter(source_market_history.type_id == Item.id)\
            .filter(source_market_history.region_id == source_region.id)\
            .filter(source_market_history.average_price != None)\
            .filter(dest_market_history.average_volume > 0)\
            .filter(dest_market_history.type_id == Item.id)\
            .filter(dest_market_history.region_id == dest_region.id)\
            .filter(dest_market_history.average_price >
                    source_market_stat.current_sell)\
            .filter(source_station.facilityID == form.source.data)\
            .filter(dest_station.facilityID == form.destination.data)\
            .order_by(dest_market_history.price_volume.desc())\
            .all()

    else:
        data = []
    return render_template(
        'crest/import.html',
        title="Import tool",
        data=data,
        form=form,
    )


@crest.route('/search', methods=['POST', 'GET'])
@login_required
def search():
    '''Returns a list of items matching search term'''
    form = SearchForm()
    if form.validate_on_submit():
        data = {}
        data["items"] = db.session.query(Item)\
            .filter(Item.name >= form.search_term.data)\
            .filter(Item.name < form.search_term.data + u"\ufffd")\
            .limit(10)
        data["regions"] = db.session.query(Region)\
            .filter(Region.name >= form.search_term.data)\
            .filter(Region.name < form.search_term.data + u"\ufffd")\
            .limit(10)
        data["systems"] = db.session.query(System)\
            .filter(System.name >= form.search_term.data)\
            .filter(System.name < form.search_term.data + u"\ufffd")\
            .limit(10)
        data["stations"] = db.session.query(Station)\
            .filter(Station.name >= form.search_term.data)\
            .filter(Station.name < form.search_term.data + u"\ufffd")\
            .limit(10)
        return render_template('crest/search.html',
                               title=form.search_term.data,
                               data=data,
                               search_term=form.search_term.data,
                               form=form)
    data = {"items": [], "regions": [], "systems": [], "stations": []}
    return render_template('crest/search.html',
                           title="Search",
                           data=data,
                           search_term="",
                           form=form)


@crest.route('/update_action', methods=['POST'])
@login_required
def update_action():
    update_form = UpdateForm()
    if update_form.validate_on_submit():
        update_tasks = (
            tasks.update_items,
            tasks.update_map,
            tasks.update_item_prices,
            tasks.update_all_item_details,
        )
        task = update_tasks[update_form.task.data]
        task.apply_async()

    update_market_form = UpdateMarketForm()
    all_regions = db.session.query(Region.id, Region.name)\
        .order_by(Region.name)\
        .all()
    update_market_form.region.choices = (all_regions)

    return render_template(
        'crest/update.html',
        title="Update",
        update_form=update_form,
        update_market_form=update_market_form,
    )


@crest.route('/update_market_action', methods=['POST'])
@login_required
def update_market_action():
    update_market_form = UpdateMarketForm()
    all_regions = db.session.query(Region.id, Region.name)\
        .order_by(Region.name)\
        .all()
    update_market_form.region.choices = (all_regions)

    if update_market_form.validate_on_submit():
        region_id = update_market_form.region.data
        items = update_market_form.items.data  # 0 all, 1 popular, 2 favs
        if update_market_form.task.data == 0:
            tasks.update_all_market_history.apply_async(
                args=(region_id, items))
        elif update_market_form.task.data == 1:
            with auth_connection() as con:
                auth_dump = dump_connection(con)
            tasks.update_all_market_stat.apply_async(
                args=(auth_dump, region_id, items)
            )

    return render_template(
        'crest/update.html',
        title="Update",
        update_form=UpdateForm(),
        update_market_form=update_market_form,
    )


@crest.route('/update', methods=['POST', 'GET'])
@login_required
def update():
    update_market_form = UpdateMarketForm()
    all_regions = db.session.query(Region.id, Region.name)\
        .order_by(Region.name)\
        .all()
    update_market_form.region.choices = (all_regions)

    return render_template(
        'crest/update.html',
        title="Update",
        update_form=UpdateForm(),
        update_market_form=update_market_form,
    )

app/templates/crest/generic.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>{{name}}</h1>
            </div>
            <table class="table">
                <thead>
                <th scope="col">Attr</th>
                <th scope="col">Val</th>
                </thead>
                <tbody>
                    {% for k, v  in data._dict.iteritems() %}
                        <tr>
                            <td> {{k}}</td>
                            <td> {{v}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div><!--/col-md--->
    </div><!--/row-->
{% endblock %}

app/templates/crest/generic_list.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>{{name}}</h1>
            </div>
            {{other_data}}
            {{link_fix}}
            <table class="table">
                <thead>
                    <th scope="col">{{table_name}}</th>
                </thead>
                <tbody>
                    {% for thing in data %}
                        <tr>
                            <td> <a href="{{link_fix + thing.name}}">{{thing.name}}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div><!--/col-md--->
    </div><!--/row-->
{% endblock %}

app/templates/crest/import.html
{% extends "base.html" %}
{% import "helpers/forms.html" as forms %}

{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>Import Tool <small>...</small></h1>
            </div>    
            <form action="{{url_for('crest.import_tool')}}" method="POST">
                {{ forms.render(form) }}
                <button type="Submit" class="btn btn-default">Submit</button>
            </form>
            <table class="table" id="example">     
                <thead>
                    <th scope="col">Item</th>
                    <th scope="col" class="text-right">Daily Vol.</th>
                    <th scope="col" class="text-right">Stock (Orders)</th>
                    <th scope="col" class="text-right">Days</th>
                    <th scope="col" class="text-right">Source Price<br>(Current Trend)</th>
                    <th scope="col" class="text-right">Destination Price<br>(Margin) [Avg Margin]</th>
                    <th scope="col" class="text-right">20% Price</th>
                </thead>
                <tbody>
                    {% for row in data %}  
                    <tr> 
                    <td><a href="/item/{{row[0].id}}">{{ row[0].name }}</a></td>
                    <td class="text-right">{{'{:20,.1f}'.format(row[3].average_volume)}}</td>
                    <td class="text-right">{{ row[1].current_sell_volume or 0 }} ({{ row[1].current_sell_orders or 0 }})</td>
                    <td class="text-right">{{'{:20,.1f}'.format((row[1].current_sell_volume or 0.0)/row[3].average_volume)}}</td>
                    <td class="text-right">{{'{:20,.0f}'.format(row[2].current_sell)}} ({{'{:20,.1f}%'.format(100*row[2].current_sell/row[4].average_price - 100)}})</td>
                    <td class="text-right">
                    {% if row[1].current_sell %}
                        {{'{:20,.0f}'.format(row[1].current_sell)}} ({{'{:20,.1f}%'.format(100*row[1].current_sell/row[2].current_sell - 100)}})
                    {% else %}
                        None
                    {% endif %}
                    [{{'{:20,.1f}%'.format(100*row[3].average_price/row[2].current_sell - 100)}}]
                    </td>
                    <td class="text-right">{{'{:20,.0f}'.format(row[5])}}</td>
                    </tr> 
                    {% endfor %} 
                <tbody>
            </table>
        </div><!--/col-md-->
    </div><!--/row-->
{% endblock %}

app/templates/crest/item_types.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>Item Types</h1>
            </div>
            crest name: {{crest_item.name}}
            <br>
            crest description:{{crest_item.description|safe}}
            <br>
            db name: {{item.name}}
            <br>
            db id: {{ item.id }}
            <br>
            db adj: {{ item.adjustedPrice }}
            <br>
            db avg:{{ item.averagePrice }}
            <br>
            db href: {{ item.href }}
            <br>
            market volume: {{ market_history.average_volume }}
            <br>
            market orders: {{ market_history.average_orders }}
            <br>
            market price: {{ market_history.average_price }}
            <br>
            stat current buy: {{ market_stat.current_buy }}
            <br>
            stat current sell: {{ market_stat.current_sell }}
            <br>
            {{item}}
            <br>
            {{market_stat}}
        </div><!--/col-md--->
    </div><!--/row-->
{% endblock %}

app/templates/crest/market_types.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>Market Types</h1>
            </div>
            <table class="table">
                <thead>
                    <th scope="col">id</th>
                    <th scope="col">name</th>
                </thead>
                <tbody>
                    {% for row in data %}
                        <tr>
                            <td>{{ row.type.id }}</td>
                            <td>{{ row.type.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div><!--/col-md--->
    </div><!--/row-->
{% endblock %}

app/templates/crest/search.html
{% extends "base.html" %}
{% import "helpers/forms.html" as forms %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
              <h1>Search <small> Items found matching: {{search_term}} </small></h1>
            </div> 
            <form action="{{url_for('crest.search')}}" method="POST">
                {{ forms.render(form) }}
                <button type="Submit" class="btn btn-default">Submit</button>
            </form>

            <table class="table table-striped">
              <thead>
                 <th scope="col">Item ID</th>
                 <th scope="col">Item Name</th>
              </thead>
              <tbody>
                    {% for item in data["items"] %}
                    </tr> 
                    <td><img src="http://image.eveonline.com/Type/{{item.id}}_32.png" class="img-polaroid"></td>
                    <td><a href="/item/{{item.id}}">{{item.name}}</a></td>
                    </tr> 
                    {% endfor %}
                    {% for region in data["regions"] %}
                    </tr> 
                    <td></td>
                    <td><a href="/region/{{region.id}}">{{region.name}}</a></td>
                    </tr> 
                    {% endfor %}
                    {% for system in data["systems"] %}
                    </tr> 
                    <td></td>
                    <td><a href="/system/{{system.id}}">{{system.name}}</a></td>
                    </tr> 
                    {% endfor %}
                    {% for station in data["stations"] %}
                    </tr> 
                    <td></td>
                    <td><a href="/station/{{station.facilityID}}">{{station.name}}</a></td>
                    </tr> 
                    {% endfor %}
              </tbody>
            </table>
        </div><!--/col-md-->
    </div><!--/row-->

{% endblock %}

app/templates/crest/station.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
            <div class="page-header">
                <h1>{{ station.name }} </h1>
            </div>
            crest name: {{crest_station.name}}
            <br>
            crest dump:{{ crest_station }}
            <br>
            db name: {{station.name}}
            <br>
            db id: {{ station.facilityID }}
            <br>
            db system: {{ station.solarSystem_id }}
            <br>
            db region: {{ station.region_id }}
            <br>
            db type id: {{ station.type_id }}
            <br>
            db href: {{ station.href }}
        </div><!--/col-md--->
    </div><!--/row-->
{% endblock %}

app/templates/crest/update.html
{% extends "base.html" %}
{% import "helpers/forms.html" as forms %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h1>Update <small> </small></h1>
        </div> 
        <div class="row">
            <div class="col-md-6">
                <h2>Universe wide:</h2>
                <form action="{{url_for('crest.update_action')}}" method="POST">
                    {{ forms.render(update_form) }}
                    <button type="Submit" class="btn btn-default">Submit</button>
                </form>
            </div> 
            <div class="col-md-6">
                <h2>Region wide:</h2>
                <form action="{{url_for('crest.update_market_action')}}" method="POST">
                    {{ forms.render(update_market_form) }}
                    <button type="Submit" class="btn btn-default">Submit</button>
                </form>
            </div> 
        </div> 
    </div><!--/col-md-->
</div><!--/row-->

{% endblock %}